@startuml Level1
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Diagrama de contexto para o Sistema de Internet Banking

SHOW_PERSON_OUTLINE()

Person(client, "Cliente bancário pessoal", "Um cliente do banco, com contas pessoais.")
System(ib, "Sistema de Internet Banking", "Permite que o cliente visualize informações sobre suas contas bancárias e faça pagamentos.")
Rel(client, ib, "Vê os saldos das contas e faz pagamentos usando")
System_Ext(email, "Sistema de E-mail", "O sistema de email interno Microsoft Exchange.")
Rel(email, client, "Envia e-mail para")
Rel(ib, email, "Envia e-mail usando")
System_Ext(mainframe, "Sistema Bancário Mainframe", "Armazena todas as informações bancárias básicas sobre clientes, contas, transações etc.")
Rel(ib, mainframe, "Obtém informações da conta e faz pagamentos usando")
@enduml