@startuml cms
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title "Mão na massa CMS"

Person(client, "Usuário", "Consumidor de conteúdo.")
Person(admin, "Admin", "Administrador de conteúdo.")

System_Boundary(cms, "Mão na massa CMS") {
Container(frontweb, "Plataforma WEB - SPA", "Vue.js", "Prover conteúdo para usuarios e acesso administrativo ao CMS.")
Container(static, "S3", "")
Container(frontmobile, "Mobile", "Flutter", "Prover conteúdo para usuarios e acesso administrativo ao CMS.")

Container(backapi, "Backend", "NestJs, Typescript", "Gerenciar e prover conteúdos da plataforma e controle de acesso.")
Container(bd, "Banco de dados SQL", "PostgreSQL", "Armazenar informações dos usuários e de conteúdo.")

Rel(client, frontweb, " Acessa o conteúdo da", "HTTPS")
Rel(client, frontmobile, "Acessa o conteudo do", "HTTPS")
Rel(admin, frontweb, " Acessa painel administrativo da", "HTTPS")
Rel(admin, frontmobile, " Acessa painel administrativo do", "HTTPS")
Rel(frontweb, backapi, " Realiza chamadas de api no", "HTTPS, JSON")
Rel(frontmobile, backapi, " Realiza chamadas de api no", "HTTPS, JSON")
Rel(backapi, bd, " Lê e escreve no")
}


@enduml
