@startuml NoShape
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(user, "Cliente", "Pessoa que precisa de produtos.")
Container(spa, "SPA", "Angular", "A principal interface com a qual o cliente interage.")
Container(api, "API", "Java", "Lida com todas as lógicas de negócios.")
Container(db, "Banco de Dados", "Microsoft SQL", "Contém informações sobre produtos, pedidos e faturas.")

Rel(user, spa, "Usa", "https")
Rel(spa, api, "Usa", "https")
Rel_R(api, db, "Lê e escreve em")
@enduml