@startuml Notation
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Notações do Modelo C4

Person(person, "Nome da pessoa", "Descrição.")
Boundary(boundary, "Nome", "Container ou Software System") {
}

System(system, "Nome do sistema", "Descrição.")
Container(container, "Nome do contêiner", "Tecnologia", "Descrição.")
Rel(system, container, "Relação", "Tecnologia")
Component(component, "Nome do componente", "Tecnologia", "Descrição.")
@enduml