@startuml Relationship
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()


System(sysa, "Sistema de Dados Comerciais")
System(sysb, "Sistema de Risco Financeiro")
Rel(sysa, sysb, "Dados comerciais")

Container(spa2, "Aplicativo de página única", "NestJS")
Container(api2, "Aplicativo API", "Python e FastAPI")
Rel(spa2, api2, "Usa")
@enduml