@startuml Relationship2
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()

System(sysc, "Sistema de Dados Comerciais")
System(sysd, "Sistema de Risco Financeiro")
Rel(sysc, sysd, "Envia dados comerciais para")

Container(spa, "Aplicativo de página única", "NestJS")
Container(api, "Aplicativo API", "Python e FastAPI")
Rel(spa, api, "Faz chamadas de API usando")

@enduml