@startuml Show
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_LEFT_RIGHT()

AddRelTag("async", $lineStyle = DashedLine())

Container(A, "Container A", "Python", "Produtor de eventos para a fila.")
Container(B, "Container B", "Java", "Consumidor de eventos da fila.")
Container(C, "Container C", "Nodejs", "Produtor de eventos para a fila.")
Container(D, "Container D", "Go", "Consumidor de eventos da fila.")

Rel(A, B, "Envia mensagem de criação de usuário", "via RabbitMQ fila CREATE", $tags="async")
Rel(C, D, "Envia mensagem de atualização de usuário", "via RabbitMQ fila UPDATE", $tags="async")
@enduml
