@startuml Level3
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Diagrama de componentes para o Sistema de Internet Banking

SHOW_PERSON_OUTLINE()
LAYOUT_LEFT_RIGHT()


Container(spa, "Aplicação de página única (SPA)","Javascript e Angular", "Fornece todas as funcionalidades de internet banking aos clientes por meio do navegador da web.")
Container(mobile, "Aplicativo móvel", "Xamarin", "Fornece um subconjunto limitado da funcionalidade de internet banking aos clientes por meio de seus dispositivos móveis.")

Container_Boundary(api, "Aplicativo API"){
  Component(signin, "Controlador de Login", "Spring MVC Rest Controller", "Permite que os usuários façam login no sistema de Internet Banking.")
  Component(security, "Componente de Segurança", "Spring Bean", "Fornece funcionalidades relacionadas a login, alteração de senha etc.")
  Component(reset, "Controlador de Redefinição de Senha", "Spring MVC Rest Controller", "Permite ao usuário redefinir suas senhas com uma URL de uso único.")
  Component(compemail, "Componente de E-mail", "Spring Bean", "Envia e-mail para os usuários.")
  Component(summary, "Controlador de Resumo de Conta", "Spring MVC Rest Controller", "Oferece aos clientes um resumo de suas contas bancárias.")
  Component(facade, "Facade do Sistema Bancário Mainframe", "Spring Bean", "Uma fachada para o sistema bancário de mainframe.")

  Rel(spa, signin, "Faz chamadas de API para", "JSON/HTTPS")
  Rel(spa, reset, "Faz chamadas de API para", "JSON/HTTPS")
  Rel(spa, summary, "Faz chamadas de API para", "JSON/HTTPS")

  Rel(mobile, signin, "Faz chamadas de API para", "JSON/HTTPS")
  Rel(mobile, reset, "Faz chamadas de API para", "JSON/HTTPS")
  Rel(mobile, summary, "Faz chamadas de API para", "JSON/HTTPS")

 
  Rel(signin, security, "Usa")
  Rel(reset, security, "Usa")
  Rel(reset, compemail, "Usa")
  Rel(summary, facade, "Usa")

}
ContainerDb(db, "Banco de Dados", "Oracle Database Schema", "Armazena informações de registro do usuário, credenciais autenticadas com hash, registros de acesso etc.")
Rel(security, db, "Lê e escreve em")
System_Ext(email, "Sistema de E-mail", "O sistema de email interno Microsoft Exchange.")
Rel(compemail, email, "Envia e-mail usando", "SMTP")
System_Ext(mainframe, "Sistema Bancário Mainframe", "Armazena todas as informações bancárias básicas sobre clientes, contas, transações etc.")
Rel(facade, mainframe, "Faz chamadas de API para", "XML/HTTPS")
@enduml