@startuml  Icons
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/java.puml
!include DEVICONS/angular.puml
!include DEVICONS/msql_server.puml

SHOW_PERSON_PORTRAIT()

Person(user, "Cliente", "Pessoa que precisa de produtos.")
Container(spa, "SPA", "Angular", "A principal interface com a qual o cliente interage.", $sprite = "angular")
Container(api, "API", "Java", "Lida com todas as lógicas de negócios.", $sprite = "java")
ContainerDb(db, "Banco de Dados", "Microsoft SQL", "Contém informações sobre produtos, pedidos e faturas.", $sprite = "msql_server")

Rel(user, spa, "Usa", "https")
Rel(spa, api, "Usa", "https")
Rel_R(api, db, "Lê e escreve em")
@enduml